// Generated by CoffeeScript 1.3.3
/*global require
*/

require.config({
  paths: {
    underscore: 'libs/underscore',
    bootstrap: 'libs/bootstrap',
    d3: 'libs/d3',
    d3layout: 'libs/d3.layout'
  },
  shim: {
    underscore: {
      exports: '_'
    },
    d3: {
      exports: 'd3'
    },
    d3layout: {
      deps: ['d3'],
      exports: 'd3'
    }
  }
});

require(['underscore', 'bootstrap', 'riskTree'], function() {
  'use strict';

});
