// Generated by CoffeeScript 1.4.0
/*global require
*/

require.config({
  paths: {
    underscore: 'libs/underscore',
    bootstrap: 'libs/bootstrap',
    d3: 'libs/d3',
    d3layout: 'libs/d3.layout'
  },
  shim: {
    underscore: {
      exports: '_'
    },
    d3: {
      exports: 'd3'
    },
    d3layout: {
      deps: ['d3'],
      exports: 'd3'
    }
  }
});

require(['riskTree', 'bootstrap'], function(riskTree) {
  'use strict';

  var successHandler;
  successHandler = function(data) {
    $('.massiveSpinner').hide();
    $('#alertNearlyThere').hide();
    $('#riskTree img').hide();
    $('#riskTree svg').remove();
    $('#riskTree').height('2000px');
    riskTree.Draw('#riskTree', data);
    return $('#alertSuccess').show();
  };
  $('#getRisk').click(function() {
    $('.massiveSpinner').show();
    $('#getRisk').css('disabled', 'disabled');
    return $.ajax('flare.json', {
      success: successHandler
    });
  });
});
