// Generated by CoffeeScript 1.4.0
/*global define
*/

define(['d3layout'], function(d3) {
  'use strict';

  var draw, fontSize, maxLabelLength, nodeRadius;
  maxLabelLength = 30;
  nodeRadius = 5;
  fontSize = 12;
  draw = function(selector, data) {
    var $target, layoutRoot, link, links, nodeGroup, nodes, size, tree;
    $target = $(selector);
    size = {
      width: $target.width(),
      height: $target.height()
    };
    tree = d3.layout.tree().size([size.height, size.width]).children(function(node) {
      if (!node.children || node.children.length === 0) {
        return null;
      } else {
        return node.children;
      }
    });
    nodes = tree.nodes(data);
    links = tree.links(nodes);
    layoutRoot = d3.select(selector).append('svg:svg').attr('width', size.width).attr('height', size.height).append('svg:g').attr('class', 'container').attr('transform', 'translate(' + 100 + ',0)');
    link = d3.svg.diagonal().projection(function(node) {
      return [node.y, node.x];
    });
    layoutRoot.selectAll('path.link').data(links).enter().append('svg:path').attr('class', 'link').attr('d', link);
    nodeGroup = layoutRoot.selectAll('g.node').data(nodes).enter().append('svg:g').attr('class', 'node').attr('transform', function(node) {
      return 'translate(' + node.y + ',' + node.x + ')';
    });
    nodeGroup.append('svg:circle').attr('class', 'node-dot').attr('r', nodeRadius);
    return nodeGroup.append('svg:text').attr('text-anchor', function(d) {
      var _ref;
      return (_ref = d.children) != null ? _ref : {
        'end': 'start'
      };
    }).attr('dx', function(d) {
      var gap, _ref;
      gap = 2 * nodeRadius;
      return (_ref = d.children) != null ? _ref : -{
        gap: gap
      };
    }).attr('dy', 3).text(function(d) {
      return d.name;
    });
  };
  return {
    Draw: draw
  };
});
