// Generated by CoffeeScript 1.3.3
/*global require
*/

require(['d3layout'], function(d3) {
  "use strict";

  var circleRadius, collapsedFillColor, diagonal, duration, expandedFillColor, height, i, margin, root, spacing, toggle, totalHeight, totalWidth, tree, update, vis, width;
  duration = 500;
  spacing = 180;
  circleRadius = 4.5;
  collapsedFillColor = "salmon";
  expandedFillColor = "#fff";
  margin = {
    top: 20,
    left: 120,
    bottom: 20,
    right: 120
  };
  totalWidth = 1130;
  totalHeight = 1000;
  width = totalWidth - margin.left - margin.right;
  height = totalHeight - margin.top - margin.bottom;
  vis = d3.select("#riskTree").append("svg:svg").attr("width", totalWidth).attr("height", totalHeight).append("svg:g").attr("transform", "translate(" + margin.right + "," + margin.top + ")");
  root = null;
  d3.json("flare.json", function(json) {
    root = json;
    root.x0 = height / 2;
    root.y0 = 0;
    return update(root);
  });
  diagonal = d3.svg.diagonal().projection(function(d) {
    return [d.y, d.x];
  });
  tree = d3.layout.tree().size([height, width]);
  i = 0;
  update = function(source) {
    var link, node, nodeExit, nodeInner, nodeUpdate, nodes;
    nodes = tree.nodes(root);
    nodes.forEach(function(d) {
      return d.y = d.depth * spacing;
    });
    node = vis.selectAll("g.node").data(nodes, function(d) {
      return d.id || (d.id = ++i);
    });
    nodeInner = node.enter().append("svg:g").attr("class", "node").attr("transform", function() {
      return "translate(" + source.y0 + "," + source.x0 + ")";
    }).on("click", function(d) {
      toggle(d);
      return update(d);
    });
    nodeInner.append("svg:circle").attr("r", 1e-6).style("fill", function(d) {
      if (d._children) {
        return collapsedFillColor;
      } else {
        return expandedFillColor;
      }
    });
    nodeInner.append("svg:text").attr("x", function(d) {
      if (d.children || d._children) {
        return -10;
      } else {
        return 10;
      }
    }).attr("dy", ".35em").attr("text-anchor", function(d) {
      if (d.children || d._children) {
        return "end";
      } else {
        return "start";
      }
    }).text(function(d) {
      return d.name;
    }).style("fill-opacity", 1e-6);
    nodeUpdate = node.transition().duration(duration).attr("transform", function(d) {
      return "translate(" + d.y + "," + d.x + ")";
    });
    nodeUpdate.select("circle").attr("r", circleRadius).style("fill", function(d) {
      if (d._children) {
        return collapsedFillColor;
      } else {
        return expandedFillColor;
      }
    });
    nodeUpdate.select("text").style("fill-opacity", 1);
    nodeExit = node.exit().transition().duration(duration).attr("transform", function() {
      return "translate(" + source.y + "," + source.x + ")";
    }).remove();
    nodeExit.select("circle").attr("r", 1e-6);
    nodeExit.select("text").style("fill-opacity", 1e-6);
    link = vis.selectAll("path.link").data(tree.links(nodes), function(d) {
      return d.target.id;
    });
    link.enter().insert("svg:path", "g").attr("class", "link").attr("d", function() {
      var o;
      o = {
        x: source.x0,
        y: source.y0
      };
      return diagonal({
        source: o,
        target: o
      });
    }).transition().duration(duration).attr("d", diagonal);
    link.transition().duration(duration).attr("d", diagonal);
    link.exit().transition().duration(duration).attr("d", function() {
      var o;
      o = {
        x: source.x0,
        y: source.y0
      };
      return diagonal({
        source: o,
        target: o
      });
    }).remove();
    return nodes.forEach(function(d) {
      d.x0 = d.x;
      return d.y0 = d.y;
    });
  };
  toggle = function(d) {
    if (d.children) {
      d._children = d.children;
      return d.children = null;
    } else {
      d.children = d._children;
      return d._children = null;
    }
  };
});
